name = "Bear Cub"
license = "GPL-3.0"
licenselink = "https://github.com/crazyc4t/hugo-bearcub/blob/master/LICENSE"
description = "Theme description"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/crazyc4t/hugo-bearcub"

# If you have a running demo of the theme.
demosite = "https://clente.github.io/hugo-bearcub"

tags = ["blog", "responsive", "minimal", "personal", "dark", "multilingual"]
features = ["favicon", "seo", "no javascript", "rss", "social cards"]

# If the theme has a single author
[author]
name = "Said Neder"
homepage = "https://saidneder.ca"

# If porting an existing theme
[original]
author = "Jan Raasch"
homepage = "https://www.janraasch.com"
repo = "https://github.com/janraasch/hugo-bearblog"

# Hugo versions the theme supports
[module]
[module.hugoVersion]
min = "0.90"
